FROM python:3.8.12-buster

COPY artia /artia
COPY requirements.txt /requirements.txt

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD uvicorn artia.artia-run:app --host 127.0.0.1 --port $PORT
#port request by google cloud run
